const ADD_PRODUCTS="ADD_PRODUCTS";
const DELETE_PRODUCTS="DELETE_PRODUCTS"
const UPDATE_PRODUCTS="UPDATE_PRODUCTS"
const UPDATE_QUANTITY="UPDATE_QUANTITY"
const DELETE_CART_PRODUCTS="DELETE_CART_PRODUCTS"
const ADD_PRODUCT_CART="ADD_PRODUCT_CART"
const SORT_PRODUCTS="SORT_PRODUCTS"
const RESET_FILTER="RESET_FILTER"
const CLEAR_CART='CLEAR_CART'
const NO_CHANGE='NO_CHANGE'
export{
    ADD_PRODUCTS,
    DELETE_PRODUCTS,
    UPDATE_PRODUCTS,
    UPDATE_QUANTITY,
    DELETE_CART_PRODUCTS,
    ADD_PRODUCT_CART,
    SORT_PRODUCTS,
    RESET_FILTER,
    CLEAR_CART,
    NO_CHANGE
}